# Generated by Django 5.2 on 2025-04-16 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise_en_charge', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_retour_prevue', models.DateTimeField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_paiement', models.CharField(blank=True, max_length=20, null=True)),
                ('date_commande', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('confirme', models.BooleanField(default=False)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
