# Generated by Django 5.2 on 2025-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
