# Generated by Django 5.2 on 2025-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='confirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
