# Generated by Django 5.2 on 2025-04-15 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_confirme_commande_date_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_prise_en_charge',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_retour_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
