# Generated by Django 5.2 on 2025-04-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('unites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='largeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_largeur', to='unites.valeurmesure'),
        ),
        migrations.AddField(
            model_name='article',
            name='longueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_longueur', to='unites.valeurmesure'),
        ),
        migrations.AddField(
            model_name='article',
            name='poids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_poids', to='unites.valeurmesure'),
        ),
    ]
