# Generated by Django 5.2 on 2025-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_email_remove_client_nom_complet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nom_complet',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
